#!/usr/bin/env bash

set -eu

staged_files_count=$(git status --porcelain | grep -E "^(A|M) " | wc -l)
[[ $staged_files_count  == "0" ]] && echo "no file staged" && exit 1

echo -e "\e[0;30mstarting to lint...\e[0m"
# wanted to "grep ✗" but it doesnt stops the commit (exit 0)
npm run lint-staged
echo -e "\e[0;30mstarting to test...\e[0m"
export NODE_ENV=test ; npm test > /dev/null
