#!/usr/bin/env bash

set -eu

echo -e "\e[0;30mstarting to lint...\e[0m"
# wanted to "grep ✗" but it doesnt stops the commit (exit 0)
npm run lint-staged
echo -e "\e[0;30mstarting to test...\e[0m"
npm run test-unit > /dev/null
