#!/usr/bin/env bash
databases=$(./scripts/print_module_exports.js server/db/couchdb/databases.js default | jq 'keys | join(" ")' -r)
dbHost=$(node -e "console.log(CONFIG.db.getOrigin())")
elasticOrigin=$(node -e "console.log(CONFIG.elasticsearch.origin)")
leveldbPathBase=$(node ./server/lib/absolute_path.js root db/leveldb)
leveldbPath="${leveldbPathBase}-tests"

for db in $databases
do
  echo "\ndeleting ${db}-tests in couchdb... " &&
  curl -sXDELETE "${dbHost}/${db}-tests"
  echo "\ndeleting ${db}-tests in elastic search... " &&
  curl -sXDELETE "${elasticOrigin}/${db}-tests"
done

echo "\ndeleting ${leveldbPath}... " &&
rm -rf ${leveldbPath}
