#!/usr/bin/env bash

if [[ -f ./run/3009-supervisor ]] ;
then
  supervisor_pid=$(cat ./run/3009-supervisor)
fi

if [[ "$supervisor_pid" != '' ]] ;
then
  kill $supervisor_pid
else
  echo "no test server to kill"
fi
