#!/usr/bin/env bash
files=$@
# If no test file is passed as argument, run all tests
[ -z "$1" ] && files=tests/api/**/*test.coffee

for arg in $@
do
  echo "$arg" | grep ".test.coffee" > /dev/null || echo -e "\e[0;33mWARNING: test file misses .test.coffee in filename: $arg\e[0m" ;
done

# Run the tests
export NODE_ENV=tests NODE_APP_INSTANCE=tests-alt; mocha --exit --require coffee-script/register $files --timeout 20000
