#!/usr/bin/env bash
files=$@
# If no test file is passed as argument, run all tests
[ -z "$1" ] && files=tests/api/**/*test.coffee

# Run the tests
export NODE_ENV=tests NODE_APP_INSTANCE=tests-alt; mocha --exit --require coffee-script/register $files --timeout 20000
