#!/usr/bin/env bash

# Use NODE_APP_INSTANCE=tests-alt to override local config with local-tests-alt
export NODE_ENV=tests-api NODE_APP_INSTANCE=server FORCE_COLOR=true

# Start a test server in the background
npm run watch > logs/test-server.log 2>&1 &
