#!/usr/bin/env bash
search_engine_path=$(node -p "require('config').entitiesSearchEngine.localPath")
cwd=$(pwd)

# Do not try to start the entities-search-engine server if updates are disabled
node -p "require('config').entitiesSearchEngine.updateEnabled || process.exit(1)" && {
  cd "$search_engine_path"
  # This value should match entities-search-engine config files
  export NODE_ENV=tests
  # NODE_APP_INSTANCE is likely to have been set by previous script
  # but is unknown by the entities_search_engine and would thus print the following warning,
  # if NODE_APP_INSTANCE was let define:
  # "WARNING: NODE_APP_INSTANCE value of 'tests-alt' did not match any instance config file names."
  export NODE_APP_INSTANCE=""
  npm start | tee "${cwd}/logs/entities_search_engine_tests.log" | grep 'server listening' &
} || exit 1

sleep 5 && echo "entitiesSearchEngine started"
