#!/usr/bin/env bash

# Use NODE_APP_INSTANCE=tests-alt to override local config with local-tests-alt
export NODE_ENV=tests-api NODE_APP_INSTANCE=server FORCE_COLOR=true

echo -e "\e[0;34mStarting test server in the background: see logs in ./logs/test-server.log\e[0;30m"
npm run watch > logs/test-server.log 2>&1 &
