#!/usr/bin/env bash

# Same as ./test_api but without deleting the databases and restarting the server
# each times: can be used to quickly run tests that don't need a complete
# environement reboot. Typically, such a dependency is due to an operation that
# isn't offered by the API at the moment (as those tests don't use as little
# server libs/controllers as possible).
# Known case: deleting an entity isn't possible from the API

if [[ -f ./run/3009-supervisor ]] ;
then
  echo -e "\e[0;32mtests server is running\e[0;30m"
else
  echo -e "\e[0;34mstarting test server\e[0;30m"
  # If the server wasn't started before, start it
  ./tests/api/scripts/start_tests_server
fi

./tests/api/scripts/run_api_tests $@
