#!/usr/bin/env sh

# In case they were running
./tests/api/scripts/kill_tests_server
# Deleting databases before the tests, so that tests can be run individually
# without having to check for the databases existance, has those will not have
# been deleted at the end of the tests
./tests/api/scripts/delete_tests_databases > /dev/null &&
./tests/api/scripts/start_tests_server &&
./tests/api/scripts/run_api_tests $@

# Kill server, even if the tests fails
./tests/api/scripts/kill_tests_server
