#!/usr/bin/env bash

find . -type f -print0 | while IFS= read -r -d $'\0' file;
  do cat $file | sed -i '0,/^$/{//d}' > $file
done

* bfa3c094 (HEAD -> delete-comment-decaf) decaffeinate: delete another type of eslint comment
* 55ec2b5b decaffeinate: delete eslint-disable comments
* d4e1d0de decaffeinate: delete suggestions
* ed7412af decaffeinate: delete lib comments "TODO" and "sanity-check"