__ = require('config').universalPath
_ = __.require 'builders', 'utils'

module.exports = (req, res, err, status)->
  # only accepts Error instances
  unless err instanceof Error
    _.error err, 'bad error object'
    return res.status(500).send(err)

  # If a status code was attached to the error, use it
  # Known case using err.statusCode: error generated by blue-cot
  status or= err.status or err.statusCode or 500

  err.user = _.pick req.user, ['_id', 'username']
  err.referer = req.headers.referer

  if /^4/.test status then _.warn err, status
  else _.error err, err.message

  res.status status
  res.json
    status: status
    status_verbose: err.message

  return