SELECT DISTINCT ?genre WHERE {
  # entities that are instances of literary genre
  { ?genre wdt:P31 wd:Q223393 . }
  # art genre
  UNION { ?genre wdt:P31 wd:Q1792379 . }
  # journalism genre
  UNION { ?genre wdt:P31 wd:Q4894405 . }
  # comedic genre
  UNION { ?genre wdt:P31 wd:Q5151404 . }
  # magazine genre
  UNION { ?genre wdt:P31 wd:Q21114848 . }
  # entities used as book genre
  UNION {
    ?book wdt:P31/wdt:P279* wd:Q571 .
    ?book wdt:P136 ?genre .
  }
  MINUS {
    # minus entities that are instances of a Wikimedia disambiguation page
    ?genre wdt:P31 wd:Q4167410 .
  }
}
