  SELECT DISTINCT ?work WHERE {
    VALUES (?work_type) { (wd:Q571) (wd:Q47461344) (wd:Q2831984) (wd:Q1004) (wd:Q1760610) (wd:Q8261) (wd:Q25379) (wd:Q386724) (wd:Q49084) (wd:Q8274) (wd:Q17518461) } .
    ?work wdt:P31 ?work_type .
    FILTER NOT EXISTS { ?work wdt:P629 ?other_work . }
  }