# A middleware to catch other middlewares errors and repackage them
# in JSON and with more readable error reports
CONFIG = require 'config'
__ = CONFIG.universalPath
_ = __.require('builders', 'utils')
error_ = __.require 'lib', 'error/error'

module.exports = (err, req, res, next) ->
  # Repackaging errors generated by body-parser
  if err.name is 'SyntaxError' and err.message.startsWith('Unexpected token')
    error_.bundle req, res, 'invalid JSON body', 400
  else
    error_.handler req, res, err
