#!/usr/bin/env zsh

export NODE_ENV=tests FORCE_COLOR=true

test_host=$(node -p "require('config').fullHost()")
entities_search_engine_host=$(node -p "require('config').entitiesSearchEngine.host")

curl -s "$entities_search_engine_host" > /dev/null && echo "entities search engine found" || \
  # Using curly brackets to group those commands without starting a subshell from which exiting would be useless
  # cf https://ss64.com/bash/syntax-brackets.html
  { echo "entities search engine not found at ${entities_search_engine_host}" && exit 1; }

# If the server is already up, return early
(curl -s "$test_host" > /dev/null || [ "$(cat run/3009)" == "starting" ]) &&
echo "server already started" &&
exit 0

# Start a test server in the background
npm run watch > logs/test-server.log 2>&1 &

# Will be replaced by the process pid once the server started
echo "starting" > run/3009

echo "waiting for server start..." &&
inotifywait run/3009 -e modify > /dev/null 2>&1 &&
echo "ok, let's go!"
