#!/usr/bin/env zsh
search_engine_path=$(node -p "require('config').entitiesSearchEngine.localPath")

{
  cd "$search_engine_path" &&
  export NODE_ENV=tests &&
  npm start | grep 'server listening' &
} || exit 1

sleep 5 && echo "entitiesSearchEngine started"
