#!/usr/bin/env sh

# If the server is already up, return early
curl -s http://localhost:3009 > /dev/null &&
echo "server already started" &&
exit 0

# Start a test server in the background
export NODE_ENV=tests FORCE_COLOR=true; npm run watch > logs/test-server.log 2>&1 &

# on '$!': http://unix.stackexchange.com/a/85022/164977
PID=$!

echo "waiting for server start..." &&
inotifywait run/3009 -e modify > /dev/null 2>&1 &&
echo "ok, let's go!"
