module.exports = [
  'Item ID',
  'Edition URI',
  'ISBN-13',
  'ISBN-10',
  'Title',
  'Subtitle',
  'Publication Date',
  'Cover',
  'Number of pages',
  'Edition Lang',
  'Works URIs',
  'Works labels',
  'Original Lang',
  'Works Series ordinals',
  'Authors URIs',
  'Authors labels',
  'Translators labels',
  'Translators URIs',
  'Series URIs',
  'Series labels',
  'Genres URIs',
  'Genres labels',
  'Subjects URIs',
  'Subjects labels',
  'Publisher URIs',
  'Publisher label',
  'Item details',
  'Item notes',
  'Item created'
].join(',')
