module.exports = [
  'Item ID',
  'Edition URI',
  'ISBN-13',
  'ISBN-10',
  'Title',
  'Subtitle',
  'PublicationDate',
  'Cover',
  'Number of pages',
  'Works URIs',
  'Works labels',
  'Works Series ordinals',
  'Authors URIs',
  'Authors labels',
  'Translators labels',
  'Translators URIs',
  'Series URIs',
  'Series labels',
  'Genres URIs',
  'Genres labels',
  'Subjects URIs',
  'Subjects labels',
  'Publisher URIs',
  'Publisher label',
  'Item details',
  'Item notes',
  'Item created'
].join(',')
