module.exports = [
  'Item URL',
  'Edition URL',
  'ISBN-13',
  'ISBN-10',
  'Title',
  'Subtitle',
  'Publication Date',
  'Cover',
  'Number of pages',
  'Edition Lang',
  'Works URLs',
  'Works labels',
  'Original Lang',
  'Works Series ordinals',
  'Authors URLs',
  'Authors labels',
  'Translators labels',
  'Translators URLs',
  'Series URLs',
  'Series labels',
  'Genres URLs',
  'Genres labels',
  'Subjects URLs',
  'Subjects labels',
  'Publisher URLs',
  'Publisher label',
  'Item details',
  'Item notes',
  'Shelves',
  'Item visibility',
  'Item transaction',
  'Item created'
].join(',')
