#!/usr/bin/env bash

set -eu

new_lang=$1

wikidata_archive=./client/public/i18n/src/wikidata/archive/$new_lang.json

./scripts/validate_lang $new_lang

echo "Starting wd props -l $new_lang > $wikidata_archive"
wd props --lang $1 > $wikidata_archive
echo '{}' > ./client/public/i18n/src/wikidata/$new_lang.json
echo "wd props done"

lang_list=./client/scripts/lib/i18n/langs.coffee

# If the language wasn't already added
head -n 1 $lang_list | grep -v $new_lang &&
# Add it
echo "Adding the new lang to the list of actively translated langs: $lang_list" &&
sed -i "s/]$/, '`echo $new_lang`' ]/" $lang_list

server=$PWD
client=$server/client

cd $client
./scripts/get_transifex_translations.coffee
npm run update-i18n

cd $server
npm run update-i18n

echo "now, think to add a defaultRegion to client/app/lib/languages_data.coffee for the new language"
