#!/usr/bin/env sh
newlang=$1

wikidataarchive=./client/public/i18n/src/wikidata/archive/$newlang.json

./scripts/validate_lang $newlang

echo "Starting wd props -l $newlang > $wikidataarchive"
wd props -l $1 > $wikidataarchive
echo "wd props done"

langList=./client/scripts/lib/i18n/langs.coffee

# If the language wasn't already added
head -n 1 $langList |grep -v $newlang &&
# Add it
echo "Adding the new lang to the list of actively translated langs: $langList" &&
sed -i "s/]$/, '`echo $newlang`']/" $langList

server=$PWD
client=$server/client

cd $client
./scripts/get_transifex_translations.coffee
npm run update-i18n

cd $server
npm run update-i18n

echo "now, think to add a defaultRegion to client/app/lib/languages_data.coffee for the new language"
