#!/usr/bin/env sh

# copies a transifexified version of the source language (en)
# to the client public folder to make it be available
# for automatic update

emailsSrc=server/lib/emails/i18n/src
emailsSrcCopy=client/public/i18n/src/emails
mkdir -p $emailsSrcCopy

echo 'transifexifing source language...'
transifexify $emailsSrc/en.json
cp $emailsSrc/en.transifex.json $emailsSrcCopy
echo "en.transifex.json copied to $emailsSrcCopy"
