#!/usr/bin/env sh
databases=$(coffee -e "console.log Object.keys(require('./server/db/couch/list.coffee')).join(' ')")
dbHost=$(coffee -e "console.log require('config').db.fullHost()")

for db in $databases
do
  printf "deleting ${db}-tests... " &&
  curl -sXDELETE "${dbHost}/${db}-tests"
done
