#!/usr/bin/env bash

set -eu

# keep A (added) and M (modified) files
# only if staged (0 space before/2 space after the letter)
staged=$(git status --porcelain | grep -E "^(A|M)" | grep -E '.js$' | sed -E 's/^\w+\s+//')

if [ -z "$staged" ]
  then
    echo 'no file to lint'
  else
    npm run lint $staged
fi
