#!/usr/bin/env bash

set -eu

./scripts/check_node_version.js

# If the client folder already exist, assume that it's a re-install
# and that all the following isn't needed
[ -e client ] && exit 0

npm run install-client
npm run update-i18n

mkdir -p logs run db/leveldb

touch ./logs/server.log ./logs/error.log
# Expected by scripts/actions/backup_databases.js
mkdir -p ./db/couchdb/backups
# Expected by scripts/test_api
mkdir -p run
# Create folders for when mediaStorage is in local mode (which is the default)
mkdir -p ./storage/users ./storage/groups ./storage/entities
touch run/3006 run/3009

if [ ! -f ./config/local.cjs ]; then
  # Create a local config file
  emptyConfigFile="
  # Override settings from ./default.js in this file
  module.exports = {
    db: {
      username: 'yourcouchdbusername',
      password: 'yourcouchdbpassword',
      port: 5984,
    }
  }
  "
  echo "$emptyConfigFile" >> ./config/local.cjs
  chmod 600 ./config/local.cjs
else
  echo './config/local.cjs file already exist: skipping creation'
fi

# See https://git-scm.com/docs/git-config#Documentation/git-config.txt-blameignoreRevsFile
git config blame.ignoreRevsFile .git-blame-ignore-revs

npm run update-jsconfig
