#!/usr/bin/env bash

which live-server > /dev/null || {
  echo "requires to have https://www.npmjs.com/package/live-server installed, either globally or just in this repo"
  echo "(it is not installed as a dev dependency as the use made of it it's not worth the subdependencies maintainance)"
  exit 1
}

mkdir -p /tmp/nodemailer-preview
live-server /tmp/nodemailer-preview