#!/usr/bin/env bash
files=$1
export NODE_ENV=tests-unit
if [ "$files" != "" ] ; then
  mocha --exit $MOCHA_OPTIONS "$files"
else
  mocha --exit $MOCHA_OPTIONS tests/unit/models/* tests/unit/libs/* tests/unit/controllers/*
fi
