#!/usr/bin/env bash

# PATCHES
# scripts/run_patches take its arguments from all the files
# in the scripts/patches directroy
# line 1: file to edit
# line 2: line to find
# line 3: line to append after

markAsPatched(){
  sed -i '1 i\//PATCHED' $1;
}

line(){
  sed $1"q;d" $2
}

patchFile(){
  echo '-------------------------'
  FILE=$HOME/$1
  NAME=$(basename $FILE)
  ORIGINAL="$2"
  APPEND="$3"
  STATUS=$(cat $FILE|grep "$APPEND")
  if [ -z "$STATUS" ]
  then
    sed -i "s/$ORIGINAL/$ORIGINAL\n$APPEND/" $FILE
    markAsPatched $FILE
    echo -e '\e[0;34m'$NAME': patched!\e[0m'
  else
    echo -e '\e[0;30m'$NAME': already patched\e[0m'
  fi
}

echo -e '\e[0;30mpatch-tools initialized\e[0m'

PATCHES=$1
if [ "$PATCHES" ]
then
  echo -e "\e[0;30mlooking for patches in folder: $PATCHES\e[0m"

  for PATCH in $(ls $PATCHES)
  do
    FILE=$PATCHES/$PATCH
    patchFile "$(line 1 $FILE)" "$(line 2 $FILE)" "$(line 3 $FILE)"
  done

  echo '-------------------------'
  echo -e '\e[0;32mpatches done!\e[0m'

else
  echo -e '\e[0;31mno patches folder provided\e[0m'
fi