#!/usr/bin/env bash

set -e

filter_files(){
  local filter=$1
  local file_names="${*:2}"
  echo "$file_names" | tr ' ' '\n' | grep "$filter" | tr '\n' ' '
}

if [ -z "$1" ]; then
  # If no test file is passed as argument, run all tests
  echo "Starting unit tests"
  ./scripts/run_unit_tests
  echo "Starting integration tests"
  ./scripts/run_integration_tests
  echo "Starting API tests"
  ./tests/api/scripts/test_api
else
  unit_tests_files=$(filter_files "tests/unit/" "$@")
  [ "$unit_tests_files" != "" ] && {
    echo "Run unit tests from $unit_tests_files"
    ./scripts/run_unit_tests $unit_tests_files
  }

  integration_tests_files=$(filter_files "tests/integration/" "$@")
  [ "$integration_tests_files" != "" ] && {
    echo "Run integration tests from $integration_tests_files"
    ./scripts/run_integration_tests $integration_tests_files
  }

  api_tests_files=$(filter_files "tests/api/" "$@")
  [ "$api_tests_files" != "" ] && {
    echo "Run API tests from $api_tests_files"
    ./tests/api/scripts/test_api_quick $api_tests_files
  }

  true
fi
