#!/usr/bin/env bash
set -eu

[ -e inventaire-i18n ] || {
  git clone https://github.com/inventaire/inventaire-i18n.git
}

cd ./inventaire-i18n
rm -rf ./dist
git checkout origin/master
git checkout -B master
git pull origin master
npm run build
cd ..
