#!/usr/bin/env bash

# Assumes inventaire/inventaire-i18n is installed or symboly linked from the project root
cd ./inventaire-i18n
git fetch origin dist
git checkout origin/dist
git checkout -B dist
