SELECT DISTINCT ?publisher WHERE {
  {
    # instances of publishers
    ?publisher wdt:P31/wdt:P279* wd:Q2085381 .
  } UNION {
    # companies that published a book
    ?publisher wdt:P31 wd:Q4830453 .
    ?item wdt:P123 ?publisher .
    ?item wdt:P31/wdt:P279* wd:Q571 .
  }
}
