// timestampedItemsIds is an array of [ item._id, item.created ] arrays
// as generated by getTimestampItemId
const byTimestamp = (a, b) => a[1] - b[1]
const getId = ([ id ]) => id

module.exports = {
  getTimestampItemId: ({ _id, created }) => [ _id, created ],

  getItemsByDate: timestampedItemsIds => {
    return timestampedItemsIds
    .sort(byTimestamp)
    .map(getId)
  },

  byTimestamp
}
