#!/usr/bin/env bash

# Generate a pre-filtered dump of humans in Wikidata to ease development setup
# cf https://github.com/inventaire/inventaire-deploy/blob/d280055/install_entities_search_engine#L24-L28

curl -s https://dumps.wikimedia.org/wikidatawiki/entities/latest-all.json.bz2 | \
  pbzip2 -cd | \
  # Prefilter to keep only entities that refer to Q5 in some way
  grep '"Q5"' | \
  head -n 100 | \
  # Keep only entities having the claim P31:Q5
  # Omit the attributes type, claims, sitelinks, keeping only info, labels, aliases and descriptions.
  wikibase-dump-filter --claim P31:Q5 --omit type,sitelinks | \
  gzip -c9 > humans.ndjson.bz2

chmod 664 humans.ndjson.bz2
